spring:
  application:
    name: sticker
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

# openAI key
openai:
  model: dall-e-2
  secret-key: "xxxxxxxxxx"
